name: google-trendle
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'testpassword'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  redis:
    image: redis
    restart: always
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - rsdata:/data
    ports:
      - 6379:6379

volumes:
  pgdata:
  rsdata: