"""Added updated_dt to user_word

Revision ID: 54330a7eb720
Revises: 46cb2bb27f76
Create Date: 2024-11-10 14:12:57.048844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54330a7eb720'
down_revision = '46cb2bb27f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_dt', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_word', schema=None) as batch_op:
        batch_op.drop_column('updated_dt')

    # ### end Alembic commands ###
