"""Trying new update-dt

Revision ID: 579a6e227d29
Revises: de58943bb7f0
Create Date: 2024-11-10 14:34:17.607424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579a6e227d29'
down_revision = 'de58943bb7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_word', schema=None) as batch_op:
        batch_op.alter_column('updated_dt',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_word', schema=None) as batch_op:
        batch_op.alter_column('updated_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
