"""Added user average

Revision ID: 688bb64f4446
Revises: a2e59d7dbf2e
Create Date: 2024-11-14 17:53:29.449709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688bb64f4446'
down_revision = 'a2e59d7dbf2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_score', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('average_score')

    # ### end Alembic commands ###
