"""Added many-to-many word database table

Revision ID: a8d961aad6a5
Revises: ceaa22b06ca0
Create Date: 2024-11-06 16:33:58.295915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d961aad6a5'
down_revision = 'ceaa22b06ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('global_attempts', sa.Integer(), nullable=False),
    sa.Column('global_average', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_word',
    sa.Column('user_id', sa.String(length=23), nullable=True),
    sa.Column('word_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_word')
    op.drop_table('word')
    # ### end Alembic commands ###
