"""bigint to char user key

Revision ID: c0f0b6b03040
Revises: a31d5771ecd1
Create Date: 2024-11-01 10:37:16.779894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f0b6b03040'
down_revision = 'a31d5771ecd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=21),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=21),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
