"""test2

Revision ID: c644bce198f9
Revises: 667fdde2da71
Create Date: 2024-11-08 19:13:45.276179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c644bce198f9'
down_revision = '667fdde2da71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nimce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=23), nullable=True),
    sa.Column('word_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nimce')
    # ### end Alembic commands ###
