"""new UserWord model

Revision ID: dd1582637d09
Revises: bef80502a13e
Create Date: 2024-11-10 15:08:42.965299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1582637d09'
down_revision = 'bef80502a13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=23), nullable=True),
    sa.Column('word_id', sa.String(length=128), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_word')
    # ### end Alembic commands ###
